name: Matrix Demo
on: push
jobs:
  build:
    # continue even if some of the jobs in the matrix fail
    continue-on-error: true
    strategy:
      matrix:
        # will run for all combinations: reason why its called a matrix
        # allows to run for different configurations
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          # add single combinations
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build


